### ISSUE TITLE
Error running kubernetes

### ISSUE THREAD

**Issue by DiegoGallegos4** [regisb/tutor#178] opened 2019-03-10 20:10 UTC
PLEASE PLEASE PLEASE READ THIS AND FOLLOW THE INSTRUCTIONS WHEN OPENING A NEW ISSUE

## Steps to reproduce

Run `tutor k8s quickstart`

Throws

```
Creating lms/cms databases...
Error: Pod with app {} does not exist. Make sure that the pod is running.
```

## Unexpected behavior

Fails on migrating databases

## Additional info (IMPORTANT)

tutor, version 3.1.0

**Comment by regisb** [comment] 2019-03-11 07:40
Closing this as a duplicate of #179. As you mentioned @DiegoGallegos4, the issue lies with the fact that commands should not be run in rapid succession.

**Closed by regisb** 2019-03-11 07:40 UTC
