### ISSUE TITLE
ERROR 1130 (HY000): Host '172.19.0.9' is not allowed to connect to this MySQL server

### ISSUE THREAD

**Issue by a20180502** [regisb/tutor#160] opened 2019-02-11 06:29 UTC
PLEASE PLEASE PLEASE READ THIS AND FOLLOW THE INSTRUCTIONS WHEN OPENING A NEW ISSUE

## Steps to reproduce

Include the exact command that you are running and that is causing an error. In case of a web error, include the URL of the page that is causing the error.

## Unexpected behavior

Include the full, exact output from the command that is causing your issue. Also include relevant error logs; for instance, to debug the LMS provide the output of `tutor local logs lms --tail=100`

## Additional info (IMPORTANT)

Provide the output of `tutor --version`.

**Comment by regisb** [comment] 2019-02-11 08:01
This is a duplicate of #156

**Closed** 2019-02-11 08:31 UTC
