### ISSUE TITLE
Host '172.18.0.9' is not allowed to connect to this MySQL server

### ISSUE THREAD

**Issue by natea** [regisb/tutor#199] opened 2019-04-17 18:12 UTC
## Steps to reproduce

Run `tutor local quickstart`

## Unexpected behavior

I get the following error (password redacted to `xxxxxxxxx`):

```
Nathans-MacBook-Pro-2:tutor nateaune$ tutor local quickstart
==================================================
        Interactive platform configuration
==================================================
Your website domain name for students (LMS) [www.myopenedx.com]
Your website domain name for teachers (CMS) [studio.openedx.com]
Your platform name/title [My Open edX]
Your public contact email address [nate@myemaildomain.com]
The default language code for the platform [en]
Activate SSL/TLS certificates for HTTPS access? Important note:this will NOT work in a development environment. [yN]
Activate Student Notes service (https://open.edx.org/features/student-notes)? [yN]
Activate Xqueue for external grader services (https://github.com/edx/xqueue)? [yN]
Configuration saved to /Users/nateaune/Library/Application Support/tutor/config.yml
Environment generated in /Users/nateaune/Library/Application Support/tutor/env
==============================================
        Stopping any existing platform
==============================================
docker-compose -f /Users/nateaune/Library/Application Support/tutor/env/local/docker-compose.yml --project-name tutor_local rm --stop --force

Going to remove tutor_local_elasticsearch_1, tutor_local_rabbitmq_1, tutor_local_mongodb_1, tutor_local_memcached_1, tutor_local_smtp_1, tutor_local_mysql_1
Removing tutor_local_elasticsearch_1 ... done
Removing tutor_local_rabbitmq_1      ... done
Removing tutor_local_mongodb_1       ... done
Removing tutor_local_memcached_1     ... done
Removing tutor_local_smtp_1          ... done
Removing tutor_local_mysql_1         ... done
================================================
        Database creation and migrations
================================================
Creating lms/cms databases...
docker-compose -f /Users/nateaune/Library/Application Support/tutor/env/local/docker-compose.yml --project-name tutor_local run --rm lms bash -e -c dockerize -wait tcp://mysql:3306 -timeout 20s
mysql -u root --password="xxxxxxx" --host "mysql" -e 'CREATE DATABASE IF NOT EXISTS openedx;'
mysql -u root --password="xxxxxxx" --host "mysql" -e 'GRANT ALL ON openedx.* TO "openedx"@"%" IDENTIFIED BY "xxxxxxx";'
Creating tutor_local_mysql_1         ... done
Creating tutor_local_smtp_1          ... done
Creating tutor_local_rabbitmq_1      ... done
Creating tutor_local_elasticsearch_1 ... done
Creating tutor_local_memcached_1     ... done
Creating tutor_local_mongodb_1       ... done
Creating tutor_local_forum_1         ... done

2019/04/17 18:07:08 Waiting for: tcp://mysql:3306
2019/04/17 18:07:08 Connected to tcp://mysql:3306
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1130 (HY000): Host '172.18.0.9' is not allowed to connect to this MySQL server
Error: Command failed with status 1: docker-compose -f /Users/nateaune/Library/Application Support/tutor/env/local/docker-compose.yml --project-name tutor_local run --rm lms bash -e -c dockerize -wait tcp://mysql:3306 -timeout 20s
mysql -u root --password="NME7mivi" --host "mysql" -e 'CREATE DATABASE IF NOT EXISTS openedx;'
mysql -u root --password="NME7mivi" --host "mysql" -e 'GRANT ALL ON openedx.* TO "openedx"@"%" IDENTIFIED BY "NME7mivi";'
Nathans-MacBook-Pro-2:tutor nateaune$ docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                  PORTS                                NAMES
fd77c4dd8bc0        regis/openedx-forum:ironwood   "/bin/sh -c './bin/u…"   19 seconds ago      Up Less than a second   4567/tcp                             tutor_local_forum_1
94860237df5e        memcached:1.4.38               "docker-entrypoint.s…"   21 seconds ago      Up 19 seconds           11211/tcp                            tutor_local_memcached_1
5d7c250bc783        mongo:3.2.16                   "docker-entrypoint.s…"   21 seconds ago      Up 18 seconds           27017/tcp                            tutor_local_mongodb_1
811f2a98c20b        mysql:5.6.36                   "docker-entrypoint.s…"   21 seconds ago      Up 18 seconds           3306/tcp                             tutor_local_mysql_1
a3c4cf3eb934        elasticsearch:1.5.2            "/docker-entrypoint.…"   21 seconds ago      Up 19 seconds           9200/tcp, 9300/tcp                   tutor_local_elasticsearch_1
9578b6a1147d        rabbitmq:3.6.10                "docker-entrypoint.s…"   21 seconds ago      Up 19 seconds           4369/tcp, 5671-5672/tcp, 25672/tcp   tutor_local_rabbitmq_1
66af0fba75ef        namshi/smtp:latest             "/bin/entrypoint.sh …"   21 seconds ago      Up 20 seconds           25/tcp                               tutor_local_smtp_1
Nathans-MacBook-Pro-2:tutor nateaune$
```

## Additional info (IMPORTANT)

```
$ tutor --version
tutor, version 3.3.4
```

**Comment by regisb** [comment] 2019-04-18 06:50
Hi @natea! This is an annoying issue, because I thought I had solved it already multiple times before...

Can you please run `tutor local logs mysql`, after triggering the error, and post the output here?

**Comment by natea** [comment] 2019-04-18 12:58
```
Nathans-MacBook-Pro-2:tutor nateaune$ tutor local quickstart
==================================================
        Interactive platform configuration
==================================================
Your website domain name for students (LMS) [www.myopenedx.com]
Your website domain name for teachers (CMS) [studio.openedx.com]
Your platform name/title [My Open edX]
Your public contact email address [nate@appsembler.com]
The default language code for the platform [en]
Activate SSL/TLS certificates for HTTPS access? Important note:this will NOT work in a development environment. [yN]
Activate Student Notes service (https://open.edx.org/features/student-notes)? [yN]
Activate Xqueue for external grader services (https://github.com/edx/xqueue)? [yN]
Configuration saved to /Users/nateaune/Library/Application Support/tutor/config.yml
Environment generated in /Users/nateaune/Library/Application Support/tutor/env
==============================================
        Stopping any existing platform
==============================================
docker-compose -f /Users/nateaune/Library/Application Support/tutor/env/local/docker-compose.yml --project-name tutor_local rm --stop --force
Stopping tutor_local_forum_1         ... done
Stopping tutor_local_memcached_1     ... done
Stopping tutor_local_mongodb_1       ... done
Stopping tutor_local_mysql_1         ... done
Stopping tutor_local_elasticsearch_1 ... done
Stopping tutor_local_rabbitmq_1      ... done
Stopping tutor_local_smtp_1          ... done
Going to remove tutor_local_forum_1, tutor_local_memcached_1, tutor_local_mongodb_1, tutor_local_mysql_1, tutor_local_elasticsearch_1, tutor_local_rabbitmq_1, tutor_local_smtp_1
Removing tutor_local_forum_1         ... done
Removing tutor_local_memcached_1     ... done
Removing tutor_local_mongodb_1       ... done
Removing tutor_local_mysql_1         ... done
Removing tutor_local_elasticsearch_1 ... done
Removing tutor_local_rabbitmq_1      ... done
Removing tutor_local_smtp_1          ... done
================================================
        Database creation and migrations
================================================
Creating lms/cms databases...
docker-compose -f /Users/nateaune/Library/Application Support/tutor/env/local/docker-compose.yml --project-name tutor_local run --rm lms bash -e -c dockerize -wait tcp://mysql:3306 -timeout 20s
mysql -u root --password="NME7mivi" --host "mysql" -e 'CREATE DATABASE IF NOT EXISTS openedx;'
mysql -u root --password="NME7mivi" --host "mysql" -e 'GRANT ALL ON openedx.* TO "openedx"@"%" IDENTIFIED BY "NME7mivi";'
Creating tutor_local_smtp_1          ... done
Creating tutor_local_rabbitmq_1      ... done
Creating tutor_local_mysql_1         ... done
Creating tutor_local_elasticsearch_1 ... done
Creating tutor_local_memcached_1     ... done
Creating tutor_local_mongodb_1       ... done
Creating tutor_local_forum_1         ... done
2019/04/18 12:58:14 Waiting for: tcp://mysql:3306
2019/04/18 12:58:14 Connected to tcp://mysql:3306
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1130 (HY000): Host '172.18.0.9' is not allowed to connect to this MySQL server
Error: Command failed with status 1: docker-compose -f /Users/nateaune/Library/Application Support/tutor/env/local/docker-compose.yml --project-name tutor_local run --rm lms bash -e -c dockerize -wait tcp://mysql:3306 -timeout 20s
mysql -u root --password="NME7mivi" --host "mysql" -e 'CREATE DATABASE IF NOT EXISTS openedx;'
mysql -u root --password="NME7mivi" --host "mysql" -e 'GRANT ALL ON openedx.* TO "openedx"@"%" IDENTIFIED BY "NME7mivi";'
Nathans-MacBook-Pro-2:tutor nateaune$ tutor local logs mysql
docker-compose -f /Users/nateaune/Library/Application Support/tutor/env/local/docker-compose.yml --project-name tutor_local logs mysql
Attaching to tutor_local_mysql_1
mysql_1           | 2019-04-18 12:58:12 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql_1           | 2019-04-18 12:58:12 0 [Note] mysqld (mysqld 5.6.36) starting as process 1 ...
Nathans-MacBook-Pro-2:tutor nateaune$
```

**Comment by regisb** [comment] 2019-04-18 13:08
With the mysql container still running, can you please run `tutor local databases` and post the output here?

(as discussed, no need to obfuscate the mysql password which is only used on your laptop)

**Comment by natea** [comment] 2019-04-18 19:37
```
Nathans-MacBook-Pro-2:tutor nateaune$ tutor local databases
Creating lms/cms databases...
docker-compose -f /Users/nateaune/Library/Application Support/tutor/env/local/docker-compose.yml --project-name tutor_local run --rm lms bash -e -c dockerize -wait tcp://mysql:3306 -timeout 20s
mysql -u root --password="NME7mivi" --host "mysql" -e 'CREATE DATABASE IF NOT EXISTS openedx;'
Starting tutor_local_mysql_1         ... done
Starting tutor_local_rabbitmq_1      ... done
Starting tutor_local_memcached_1     ... done
Starting tutor_local_elasticsearch_1 ... done
Starting tutor_local_mongodb_1       ... done
Starting tutor_local_forum_1         ... done
2019/04/18 19:36:58 Waiting for: tcp://mysql:3306
2019/04/18 19:36:58 Connected to tcp://mysql:3306
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1130 (HY000): Host '172.18.0.8' is not allowed to connect to this MySQL server
Error: Command failed with status 1: docker-compose -f /Users/nateaune/Library/Application Support/tutor/env/local/docker-compose.yml --project-name tutor_local run --rm lms bash -e -c dockerize -wait tcp://mysql:3306 -timeout 20s
mysql -u root --password="NME7mivi" --host "mysql" -e 'CREATE DATABASE IF NOT EXISTS openedx;'
mysql -u root --password="NME7mivi" --host "mysql" -e 'GRANT ALL ON openedx.* TO "openedx"@"%" IDENTIFIED BY "NME7mivi";'
```

**Comment by regisb** [comment] 2019-04-19 16:39
(For reference, there are similar issues: https://github.com/regisb/tutor/issues?utf8=%E2%9C%93&q=is%3Aissue+%22is+not+allowed+to+connect+to+this+MySQL+server%22)

Can you tell me a little more about your platform? Are you trying to upgrade from Hawthorn? from an earlier tutor version? If yes, which one?

Then, please run the following commands and paste the output here:

1. Check bind address:

    docker exec -it tutor_local_mysql_1 mysqld --verbose --help | grep bind-address

2. Check users:

    docker exec -it tutor_local_mysql_1 mysql -u root --password=NME7mivi1
    SELECT host, user FROM mysql.user;

**Comment by natea** [comment] 2019-04-19 16:42
I believe it was an upgrade from an earlier version of Tutor that was targeting Hawthorn, not Ironwood. Sorry, I don't remember the Tutor version.

Here's the output of those two commands:

```
Nathans-MacBook-Pro-2:tutor nateaune$ docker exec -it tutor_local_mysql_1 mysqld --verbose --help | grep bind-address
  --bind-address=name IP address to bind to.
bind-address                                               *
Nathans-MacBook-Pro-2:tutor nateaune$ docker exec -it tutor_local_mysql_1 mysql -u root --password=NME7mivi1
SELECT host, user FROM mysql.user;Warning: Using a password on the command line interface can be insecure.

ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```

**Comment by regisb** [comment] 2019-04-19 17:03
Ok so the root password is incorrect. The root and the openedx passwords used to be identical, but they were recently set so that they now have different values. So let's try with the current open edx password. Run and paste the result of:

    tutor config printvalue OPENEDX_MYSQL_PASSWORD
    tutor config printvalue MYSQL_ROOT_PASSWORD
    docker exec -it tutor_local_mysql_1 mysql -u root --password=$(tutor config printvalue OPENEDX_MYSQL_PASSWORD)
    SELECT host, user FROM mysql.user;

**Comment by natea** [comment] 2019-04-19 17:05
```
Nathans-MacBook-Pro-2:tutor nateaune$ tutor config printvalue OPENEDX_MYSQL_PASSWORD
NME7mivi
Nathans-MacBook-Pro-2:tutor nateaune$ tutor config printvalue MYSQL_ROOT_PASSWORD
NME7mivi
Nathans-MacBook-Pro-2:tutor nateaune$ docker exec -it tutor_local_mysql_1 mysql -u root --password=$(tutor config printvalue OPENEDX_MYSQL_PASSWORD)
SELECT host, user FROM mysql.user;Warning: Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```

**Comment by regisb** [comment] 2019-04-19 17:07
Did you upgrade from a pre-`tutor` version, when we were still using `make` commands instead of the `tutor` binary?

**Comment by regisb** [comment] 2019-04-19 17:08
Also, what is the output of `ls -lh $(tutor config printroot)/data/mysql`?

**Comment by natea** [comment] 2019-04-20 20:28
i changed computers and i think i installed Tutor from scratch (not from the previous openedx-docker that used make files), but I'm not sure.

```
Nathans-MacBook-Pro-2:tutor nateaune$ tutor config printroot
/Users/nateaune/Library/Application Support/tutor
```

Notice the space in the directory path, hence the need for quotes around the path.

```
Nathans-MacBook-Pro-2:tutor nateaune$ ls -lh "/Users/nateaune/Library/Application Support/tutor/data/mysql"
total 221192
-rw-rw----@  1 nateaune  staff    56B Feb 11 10:27 auto.cnf
-rw-rw----@  1 nateaune  staff    48M Apr 18 08:58 ib_logfile0
-rw-rw----@  1 nateaune  staff    48M Feb 11 10:27 ib_logfile1
-rw-rw----@  1 nateaune  staff    12M Apr 18 08:58 ibdata1
drwx------@ 81 nateaune  staff   2.5K Feb 11 10:27 mysql
drwx------@ 55 nateaune  staff   1.7K Feb 11 10:27 performance_schema
drwx------@  2 nateaune  staff    64B Feb 11 10:27 test
```

**Comment by regisb** [comment] 2019-04-21 08:14
In that case, we can simply trash the existing mysql data, which do not contain any open edx data. It's frustrating, because we did not elucidate the issue, but it should fix the problem. Just stop any running platform, clear the data and restart:

    tutor local stop
    sudo rm -rf "$(tutor config printroot)/data/mysql"
    tutor local quickstart

**Comment by natea** [comment] 2019-04-21 19:05
That seems to have solved the problem as I can now see the site at http://localhost and http://studio.localhost

Any idea why www.myopenedx.com and studio.myopenedx.com don't resolve, even thought i've added them to my /etc/hosts file?

**Comment by regisb** [comment] 2019-04-21 19:18
Ok, great. I'll close this then.

> Any idea why www.myopenedx.com and studio.myopenedx.com don't resolve, even thought i've added them to my /etc/hosts file?

No, this is strange. On Linux the changes made to /etc/hosts are taken into account immediately in the browser.

Apparently, on Mac OS you may need to flush the DNS cache; this is an info that I found here https://www.tekrevue.com/tip/edit-hosts-file-mac-os-x/

**Closed by regisb** 2019-04-21 19:18 UTC

**Comment by zhaojunmo** [comment] 2020-03-04 03:03
> Ok so the root password is incorrect. The root and the openedx passwords used to be identical, but they were recently set so that they now have different values. So let's try with the current open edx password. Run and paste the result of:
> 
> ```
> tutor config printvalue OPENEDX_MYSQL_PASSWORD
> tutor config printvalue MYSQL_ROOT_PASSWORD
> docker exec -it tutor_local_mysql_1 mysql -u root --password=$(tutor config printvalue OPENEDX_MYSQL_PASSWORD)
> SELECT host, user FROM mysql.user;
> ```

I run `tutor local quickstart` the first time and found this issue, can you tell me how to solve it?
```
tutor --version
tutor, version 3.11.5
tutor config printvalue OPENEDX_MYSQL_PASSWORD
D77q5dJW
tutor config printvalue MYSQL_ROOT_PASSWORD
gdBQRWAG

docker info
Client:
 Debug Mode: false

Server:
 Containers: 24
  Running: 9
  Paused: 0
  Stopped: 15
 Images: 227
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: error
  NodeID:
  Error: error while loading TLS certificate in /var/lib/docker/swarm/certificates/swarm-node.crt: certificate (1 - mwqsonn5p9f9oyjm3hqzo8lq1) not valid after Thu, 03 Jan 2019 02:44:00 UTC, and it is currently Tue, 03 Mar 2020 13:16:12 UTC: x509: certificate has expired or is not yet valid
  Is Manager: false
  Node Address: 192.168.65.3
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.943GiB
 Name: docker-desktop
 ID: ZSUM:R4NT:HX6P:KX4W:RNUM:P2PU:6COR:4Z6Y:FCM6:M3VL:SSHS:CDU6
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 100
  Goroutines: 113
  System Time: 2020-03-04T03:00:53.9595627Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```
My platform is macOS Catalina Version 10.15.3(19D76), thank you.

**Comment by regisb** [comment] 2020-03-09 08:57
Hi @zhaojunmo! You seem to have a different issue than the OP. Also, the tutor code base has significantly changed since April 2019. If you still face this issue, I encourage you to talk about it on the official forums: https://discuss.overhang.io Github issues are for tutor bugs, and we don't know yet if your issue is caused by a bug.
