### ISSUE TITLE
DJANGO_SETTINGS_MODULE not set for lms&cms in local mode

### ISSUE THREAD

**Issue by hanqingliu** [regisb/tutor#224] opened 2019-06-21 08:17 UTC
**Bug description**
When lauch site in local mode, lms&cms cannot use tutor.production settings as DJANGO_SETTINGS_MODULE is not set.

**How to reproduce**
Run tutor local quickstart with master branch.

**Environment**
ubuntu 16.04

**Additional context**
In openedx image build process, the DJANGO_SETTINGS_MODULE is set in entrypoint.sh. But when try to lauch platform in local host, the entrypoint is override by the init file which does not set DJANGO_SETTINGS_MODULE.

**Comment by regisb** [comment] 2019-06-21 10:20
Hi @hanqingliu! I'm not sure I understand what the problem is. Is there a stacktrace or an error message?

**Comment by regisb** [comment] 2019-06-23 13:51
@hanqingliu I think I stumbled upon the same issue as you during development. This is now fixed in v3.4.2. Can you please confirm?
Thanks for reporting this issue!

**Closed** 2019-06-23 13:50 UTC

**Comment by hanqingliu** [comment] 2019-06-25 23:15
Thanks for the update, I will confirm.

Régis Behmo <notifications@github.com> 于 2019年6月21日周五 下午6:20写道：

**Comment by hanqingliu** [comment] 2019-06-28 07:32
@regisb Thanks for the quick fix, it works in my environment.
