### ISSUE TITLE
pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by natea** [regisb/tutor#119] opened 2019-01-06 22:51 UTC
## Steps to reproduce

After running `make all` and looking in the kube dashboard, it shows that several of the deployments failed. 

## Unexpected behavior

It's showing the error `pod has unbound immediate PersistentVolumeClaims` for the lms, cms and nginx pods.

![overview_-_kubernetes_dashboard](https://user-images.githubusercontent.com/118984/50742603-a11c3080-11db-11e9-8a52-d79bfd173b22.png)

## Additional info (IMPORTANT)

Include the output of the `make info` command.

When I run this command, it says, `make: *** No rule to make target `info'.  Stop.`

**Comment by regisb** [comment] 2019-01-07 07:01
I managed to reproduce this: it happens because the PersistentVolumeClaims take a little a longer to create. Just wait a couple minutes and it should switch to green again.

**Comment by regisb** [comment] 2019-01-18 06:55
@natea can I close this?

**Comment by natea** [comment] 2019-01-26 23:53
sorry i got pulled away from these investigations and haven't been able to
return to them recently. feel free to close it, and if i'm still encountering
the issue, i'll reopen it.  





On Fri, Jan 18, 2019 1:55 AM, Régis Behmo notifications@github.com  wrote:
@natea  can I close this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.





Website:http://www.appsembler.comBlog: http://www.appsembler.com/blogTwitter:
http://twitter.com/nateaLinkedIn:http://linkedin.com/in/natea
Phone: +1 (617) 702-4331

**Comment by regisb** [comment] 2019-01-27 07:01
:+1:

**Closed by regisb** 2019-01-27 07:01 UTC
